bigcommerce/sample-app-nodejs

- lib/dbs/mysql.ts
- scripts/db.js
Adds a check for MySQL env vars before falling back to ClearDB for connection. 
Jira: [APPEX-167](https://jira.bigcommerce.com/browse/APPEX-167)
...
Verified locally
...
> feat(common): APPEX-167 Fix MySQL support for generic mysql servers

- context/session.tsx
- pages/_app.tsx
- pages/index.tsx
- types/data.ts
Creates a better persistence of session across all pages.
If we end up loading the app on the `/products` page, we'll get the context from the load URL and pass it into the session context.
> fix(common): persistant session across pages

- package-lock.json
- package.json
- pages/_app.tsx
Adds a `ThemeProvider` to the application.
Provides a way to use the theme when building styled-components.
For example,
```tsx
import styled from 'styled-components';
const StyledDl = styled.dl`
color: ${({ theme }) => theme.colors.secondary70};
line-height: ${({ theme }) => theme.lineHeight.medium};
`;
```
> feat(common): add ThemeProvider to _app.tsx

- pages/api/load.ts
Use the JWT token `url` key/value to load redirect URL.
This allows paths to be provided when the app loads. For instance, we want to load `/app/6/orders/100?foo=1&bar=2` the app will now be able to redirect to `/orders/100?context=<encodedContext>&foo=1&bar=2`.
Params passed into the app:
> feat(common): use jwt url value for load redirect

- components/error.tsx
- components/header.tsx
- lib/auth.ts
- lib/hooks.ts
- pages/_app.tsx
- pages/api/load.ts
- pages/api/orders/[orderId]/index.ts
- pages/orders/[orderId]/modal.tsx
- types/error.ts
- types/index.ts
- types/order.ts
Builds off of #69 & #70.
Adds a modal view for viewing orders.
Primarily builds off of #69 to support deep linking within modals. This is an example view we might ship out.
> feat(common): add order page for modal

- lib/auth.ts
- types/auth.ts
Adds support for testing in different environments. Note: we cannot rely on `process.env.NODE_ENV` as `next start` will return 'production.'
We need to be able to utilize testing api hosts on non-production targets.
Verified by installing/ loading the app, linting, established production build and TypeScript by running npm run build.
> feat(common): APPEX-204 add api support for testing

- lib/dbs/mysql.ts
Implement mysql connection pooling to automatically handle server disconnects. See:
- https://www.npmjs.com/package/mysql#server-disconnects
- https://www.npmjs.com/package/mysql#pooling-connections
Note that, because a ClearDB connection string is utilized rather than mysql connection options when deploying to Heroku, it is not possible to define a connectionLimit in the [pool options](https://www.npmjs.com/package/mysql#pool-options). As a result the default value (10) is used.
The following error was present in logs locally and on heroku resulting in app crashes:
```
error - uncaughtException: Error: Connection lost: The server closed the connection.
at Protocol.end (/Users/patrick.puente/node-projects/demo-tax-provider/node_modules/mysql/lib/protocol/Protocol.js:112:13)
at …
```
> Implement mysql connection pooling

- README.md
Adds info about the `npm run db:setup` command that must be run if using mysql.
Was missing this step from the README.
N/A
> Update README.md to add mysql setup

- lib/auth.ts
- lib/dbs/firebase.ts
- lib/dbs/mysql.ts
- types/db.ts
- Adds `deleteStoreUsers` method to both firebase and mysql modules to be called from `removeDataStore` on uninstall. - - Fixes `deleteStore` method.
[APPEX-279](https://bigcommercecloud.atlassian.net/browse/APPEX-279)
...
Verified manually for both Firebase and MySQL.
...
> fix(common): APPEX-279 delete all store users on uninstall

- README.md
- next-env.d.ts
- package-lock.json
- package.json
- tsconfig.json
STEP 1: Upgrades NextJS to 12. As part of the update, this gives a minor bump to React (we're unable to upgrade React to 18 as Big-Design does not yet support React v18). This PR also updates BigDesign, styled-components, and typescript.
Security vulnerabilities
verified locally and by running the app on a prod store; confirmed build passing
> feat(common): appex-274 step 1 upgrade next, react, and BigDesign

- README.md
- lib/db.ts
- lib/dbs/firebase.ts
- lib/dbs/mysql.ts
- next-env.d.ts
- package-lock.json
- package.json
- pages/index.tsx
- tsconfig.json
- types/db.ts
- types/index.ts
STEP 3: Upgrades NextJS to 12. As part of the update, this gives a minor bump to React (we're unable to upgrade React to 18 as Big-Design does not yet support React v18). This PR also updates Firebase, styled-components, as well as most other dependencies.
Security vulnerabilities
verified locally and by running the app on a prod store; confirmed build passing
> feat(common) appex-274 step 3 upgrade next, react, firebase, and other libraries

- lib/dbs/mysql.ts
- scripts/db.js
- types/db.ts
Adds mysql support to the checkout reference application.
Needed for release
deployed to Heroku, verified clearDB populated with correct checkout and plan info. Also ran linting, tests, and confirmed build.
> feat(common): adds sql support

- pages/api/checkout/removeWelcome.ts
Noticed a bug while demoing - the welcome alert may not show if the iframe temporarily shows a duplicate frame when redirecting back to the app. 
Welcome alert not displaying
locally and on staging, verified build and test passing
> fix(common): fix welcome alert

- README.md
Updates links to Sample App quickstart guide in the docs.
Broken links from docs update
...
> fix(common): APPEX-448 updates docs links in README step 2

- README.md
Updates README links to Sample App quickstart guide in the docs.
Broken links from docs update
...
> fix(common): APPEX-448 updates docs links in README step 3

- README.md
Updates README links to Sample App quickstart guide in the docs.
Broken links from docs update
...
> fix(common): APPEX-448 updates docs links in README step 4

- README.md
Updates README links to Sample App quickstart guide in the docs.
Broken links from docs update
...
> fix(common) APPEX-448 updates docs links in README

- components/header.tsx
- pages/product/[productId]/index.tsx
- test/pages/__snapshots__/index.spec.tsx.snap
- test/pages/product/__snapshots__/index.spec.tsx.snap
- test/pages/product/index.spec.tsx
- test/pages/products/__snapshots__/[pid].spec.tsx.snap
- test/pages/products/__snapshots__/index.spec.tsx.snap
Adding in the ability to see an example of App Extensions with the already loaded products list on headerless route product/productId
To give app developers  a reference  of App Extensions implementation of it in the Node Sample App
...
https://user-images.githubusercontent.com/109627308/209204736-d68be80b-2ccb-4279-8c38-578633f21c1c.mov
> feat(appext): APPEX-359 Add refernce example using App Extensions

- lib/checkout.ts
Updated _trial_days_ to _trialDays_ for proper syntax.
The trial days property previously used the "trial_days" syntax which was incorrect and ignored but the Checkout Mutation. 
See [syntax documentation](https://bigcommerce.stoplight.io/docs/beta-automated-billing/b35cc8558d171-schema-types#pricingplaninput)
> update trialDays prop on plan with proper syntax

- package-lock.json
- package.json
What?
When trying to upgrade BigDesign theme from 0.17 to 0.18 we’re receiving a peer dependency issue requiring React to be version 18. React was version 17 in the Sample App.
Why?
Upgraded to React/DOM/TYPES to latest
Next to 12.3.3
Styled Components to 5.3.10 for latest version
BigDesign to 0.36
Testing / Proof
Tested Locally App Running
> chore(appex):Upgrading Dependencies Versions

- package-lock.json
- package.json
What?
When trying to upgrade BigDesign theme from 0.17 to 0.18 we’re receiving a peer dependency issue requiring React to be version 18. React was version 17 in the Sample App.
Why?
Upgraded to React/DOM/TYPES to latest
Next to 12.3.3
Styled Components to 5.3.10 for latest version
BigDesign to 0.36
Testing / Proof
Tested Locally App Running
> chore(appex):Upgrading Step 2 Dependencies Versions

- package-lock.json
- package.json
What?
When trying to upgrade BigDesign theme from 0.17 to 0.18 we’re receiving a peer dependency issue requiring React to be version 18. React was version 17 in the Sample App.
Why?
Upgraded to React/DOM/TYPES to latest
Firebase to 9.14.0( to match main)
JSONWEBTOKEN (to match main)
Next to 12.3.3 (to match main)
Styled Components to 5.3.10 for latest version
BigDesign to 0.36
Testing / Proof
Tested Locally App Running
> chore(appex):Upgrading Step 3 Dependencies Versions

- package-lock.json
- package.json
What?
When trying to upgrade BigDesign theme from 0.17 to 0.18 we’re receiving a peer dependency issue requiring React to be version 18. React was version 17 in the Sample App.
Why?
Upgraded to React/DOM/TYPES to latest
Next to 12.3.3 (to match main)
Firebase to  9.14 (to match main)
JSONWEBTOKEN to 9.0.0 (to match main) 
Styled Components to 5.3.10 for latest version
BigDesign to 0.36
Testing / Proof
Tested Locally App Running
> chore(appex):Upgrading Step 4 Dependencies Versions

- lib/appExtensions.ts
- package-lock.json
- package.json
- pages/api/auth.ts
- pages/api/load.ts
- test/pages/__snapshots__/index.spec.tsx.snap
- test/pages/appExtensions.spec.ts
- test/pages/productAppExtension/__snapshots__/index.spec.tsx.snap
- test/pages/products/__snapshots__/[pid].spec.tsx.snap
- test/pages/products/__snapshots__/index.spec.tsx.snap
As part of App Extensions GA, it would be nice to have a corresponding implementation to match the tutorial. This should include API calls to create the app extension (on install/ load) and delete when the app is uninstalled.  As part of this, we should build out products in a similar fashion to orders/orderId whereby the header is scrubbed for display in the side panel.
To provide a visual example to go along with the documentation of how App Extensions work within a tutorial.
...
https://github.com/bigcommerce/sample-app-nodejs/assets/109627308/c417f895-c3e9-4413-971f-235913dd8838
https://github.com/bigcommerce/sample-app-nodejs/assets/109627308/0d130914-c01f-45c7-b55e-e807e7df900e
> feat(appex): APPEX-515 Create App Ext Reference

- .env-sample
- pages/api/load.ts
Fix for accessToken request in load for (fb and sql db).  Also added in API url to .env for reference
Prior getStoreToken broke for SQL db users.
https://github.com/bigcommerce/sample-app-nodejs/assets/109627308/6d4c054c-340b-418e-8c20-108544f4fa5e
> (fix): AccessToken for sql and fb db and .env url

- lib/appExtensions.ts
- lib/dbs/firebase.ts
- lib/dbs/mysql.ts
- package-lock.json
- pages/api/auth.ts
- pages/api/load.ts
- test/pages/appExtensions.spec.ts
- types/db.ts
Add logs when app extensions scope is missing.
Check to see if the app has the appropriate scope (app extensions) enabled to register an app extension.
Tested locally with both mysql and firebase dbs
**Showing logs when app extensions scope is missing**
https://github.com/bigcommerce/sample-app-nodejs/assets/39739180/219e44e6-8ced-4f9b-bc11-a87ad5f0d25b
**Not showing logs when scope exists**
https://github.com/bigcommerce/sample-app-nodejs/assets/39739180/fa18f820-1171-4cbd-ae1f-4a481734951f
> (feat): APPEX-540 check scopes when registering an app extension

- package-lock.json
- package.json
Updates outdated packages including big-design and dotenv.
security vulnerabilities. 
locally
> APPEX-579: updates bd icons and dotenv packages

- lib/dbs/mysql.ts
- package-lock.json
- package.json
- scripts/db.js
Replaces the existing `mysql` package with `mysql2`, which effectively builds on the original package but adds additional support for mysql 8x. This PR Should address the issue noted by https://github.com/bigcommerce/sample-app-nodejs/issues/168
existing mysql package lacked support for mysql 8's advanced auth - only legacy auth was supported.
locally/ integration using both legacy and new mysql 8 auth - confirmed build, uninstall and install
> feat(common): APPEX-583 adds mysql8 auth support

- README.md
* fix readme syntax that caused suboptimal markdown rendering
* suboptimal markdown parser did not properly pick up the end of a fenced code block, which made part of the readme appear as though instructions were code blocks
~~https://github.com/slsriehl/sample-app-nodejs/blob/082079baaecac920cf599367db32f27201c65fa4/README.md~~
https://github.com/slsriehl/sample-app-nodejs/blob/b4a766afe447105420e809d7ff8fcfba6b94061e/README.md
> fix readme syntax that caused suboptimal markdown rendering

- .github/workflows/validate-workflow.yml
- README.md
- package.json
Remove testing/support for node 16 (post-EOL)
Node 16 is EOL.
> chore(common): Remove node 16 build
