lib/hooks.ts
pages/api/products/list.ts
pages/products/index.tsx
test/mocks/hooks.ts
test/pages/products/__snapshots__/index.spec.tsx.snap

Adds pagination to the product list in sample app including selectable items per page.
Jira: [APPEX-78](https://jira.bigcommerce.com/browse/APPEX-78)
...
Tests passing and verified locally. 
...

feat(common): APPEX-78 Add product list pagination to sample app

---

README.md
next-env.d.ts
package-lock.json
package.json
test/pages/__snapshots__/index.spec.tsx.snap
test/pages/products/__snapshots__/[pid].spec.tsx.snap
test/pages/products/__snapshots__/index.spec.tsx.snap
test/pages/products/index.spec.tsx

Updates sample app to use NPM 7+. This effectively creates a new package-lock file using `lockfileVersion` 2. This PR also updates big-design, NextJS (fixes security vulnerability), and styled-components. Unit tests/ snapshots also updated.
Addresses security vulnerabilities and ensures compatibility with workspaces.
verified by running the app, linting, unit tests, and creating a new build.

feat(common): updates npm, packages, and tests

---

context/session.tsx
lib/hooks.ts
pages/index.tsx
types/data.ts

Refactor to keep step 4 session context up to date with main branch. 
Jira: [APPEX-212](https://jira.bigcommerce.com/browse/APPEX-212)
Builds successfully, verified locally.

feat(common): APPEX-212 update step 4 session context

---

context/session.tsx
pages/index.tsx
types/data.ts

Refactor to update step 3 session context.
Jira: [APPEX-212](https://jira.bigcommerce.com/browse/APPEX-212)
Builds successfully, verified locally.

feat(common): APPEX-212 update step 3 session context

---

lib/dbs/firebase.ts
package-lock.json
package.json

Updates Firebase to v9. This PR also updates `babel-plugin-styled-components` as `styled-components` was recently updated and I was receiving an error, `Warning: Prop className did not match.`
To function properly with our tutorials.
Verified by installing/ loading the app, linting, established production build and TypeScript by running npm run build.

feat(common): update firebase version

---

lib/auth.ts
lib/dbs/firebase.ts
lib/dbs/mysql.ts
types/db.ts

Reverts bigcommerce/sample-app-nodejs#95

Revert "fix(common): APPEX-279 delete all store users on uninstall"

---

.github/workflows/validate-workflow.yml
README.md
package-lock.json
package.json

Fixes an issue when attempting to deploy the sample app via Heroku. This PR also updated engines (minimum node and npm versions).
[Issue #88 ](https://github.com/bigcommerce/sample-app-nodejs/issues/88)
pushed branch to my fork and verified deploy was successful. also ran tests, linting, and verified app runs locally.

feat(common): APPEX-314 fix heroku deploy

---

README.md
package-lock.json
package.json

Step 3 - Updates Sample App to use Node v14. This PR also updates BigDesign and NextJS to latest.
To keep the Sample App up to date
locally and verified build passed

feat(common): step-3 update node and BigDesign

---

README.md
components/form.tsx
components/header.tsx
package-lock.json
package.json
pages/index.tsx
pages/products/index.tsx

Step 4 - Updates Sample App to use Node v14.  This PR also updates BigDesign and NextJS to latest.
To keep the Sample App up to date
locally and verified build passed

feat(common): step-4 update node and BigDesign

---

package-lock.json
package.json

Updates BigDesign packages
Synk alerts
locally, verified by running linting, unit tests, and confirmed app builds

feat(common): appex-379 updates BigDesign

---

.env-sample
lib/auth.ts
lib/checkout.ts
lib/dbs/firebase.ts
pages/api/checkout/[pid].ts
pages/api/checkout/removeWelcome.ts
pages/api/load.ts
pages/api/subscription/index.ts
pages/index.tsx
types/db.ts

Fixes an issue whereby clearing the upgrade message would happen at the same time as setting it, creating a race condition. This PR also renames subscription functions to checkout and organizes checkout methods to be together.
to fix a bug
locally, verified unit tests passing, linting, and build passing

fix(common): fixes upgrade alert race condition

---

package-lock.json
package.json
test/pages/__snapshots__/index.spec.tsx.snap
test/pages/products/__snapshots__/[pid].spec.tsx.snap
test/pages/products/__snapshots__/index.spec.tsx.snap

Updates big-design, firebase and styled-components dependencies and updates snapshots for BD and styled-components.
Snyk alerts
Tests passing and verified running/build/lint locally

feat(common): appex-447 updates big-design/firebase/styled-components

---

package-lock.json
package.json

Updates next to `12.3.2` and @bigcommerce/big-design-theme to `0.17.0`.
Snyk alerts, Snyk update one version behind latest next v12 patch
Tests passing and verified running/build/lint locally

feat(common): APPEX-447 updates next, big-design-theme

---

README.md
package-lock.json
package.json
scripts/db.js

Updates package.json to include `dotenv` package as this is required for the db seed script. This PR also updates the node and npm engines to capture more recent versions. Finally, the readme file has been updated for clarity.
`scripts/db` was not running properly
locally

feat(common): APPEX-509 update package.json and readme

---

.env-sample

Update .env-sample file
Include the corresponding dev config.
n/a

chore(appex): update .env-sample file

---

.env-sample
README.md

A description about what this pull request implements and its purpose. Try to be detailed and describe any technical details to simplify the job of the reviewer and the individual on production support.
Update the README to better align with supporting documentation.
...
...

refresh readme

---

README.md
package-lock.json
package.json

Updates `step-1-app-foundation` to sync recent changes with main. Included in this are modifications to readme and package dependencies.
tutorial steps were out of date
locally/ integration - verified units, build passing

feat(common): APPEX-597 update step 1 to sync with main

---

.env-sample
README.md
lib/auth.ts
package-lock.json
package.json

Updates `step-2-connect-to-bc` to sync recent changes with main. Included in this are modifications to readme, .env-sample, and package dependencies.
tutorial steps were out of date
locally/ integration - verified units, build passing

feat(common): APPEX-597 update step 2 to sync with main

---

.env-sample
README.md
lib/auth.ts
lib/db.ts
lib/dbs/firebase.ts
lib/dbs/mysql.ts
package-lock.json
package.json
pages/api/load.ts
pages/api/uninstall.ts
types/auth.ts
types/db.ts

Updates `step-3-add-database` to sync recent changes with main. Included in this are modifications to readme, .env-sample, package dependencies, and db changes. 
tutorial steps were out of date
locally/ integration - verified units, build passing

feat(common): APPEX-597 update step 3 to sync with main

---

README.md
lib/auth.ts

Adds missing changes to auth
won't function in dev without
locally, integration

feat(fix): APPEX-597 adds missing auth changes

---

scripts/db.js

Updates the db seed script to function properly - includes latest `mysql2` package as well as support for reading environment variables.
forgot to include as part of updating step 3
locally

feat(common): APPEX-597 adds updates to db script
